### ISSUE TITLE
Finished with review: one last issue

### ISSUE THREAD

**Issue by ankitkalia1195** [nuugut/nimble-test#13]
Hi @nuugut , I am finishing the review now, you will hear from recruitment team in some time. 

Just wanted to point out last concern, that the password field in database is not secure, passwords are stored as plain strings in database, which is something should not be done when building a user authentication.

Anyways, you will hear from our recruitment team soon, wish you best of luck.

**Comment by gutakk** [comment]
@ankitkalia1195 Thank you so much for your time.

Could you please clarify what you concern?

I hashed password before store to database. you can see in this code
https://github.com/nuugut/nimble-test/blob/40f9ed0b5203f6c0cfb802c3062c8b68d96aabd7/backend/controllers/user.py#L21

I'm using werkzeug.security generate_password_hash function
https://werkzeug.palletsprojects.com/en/1.0.x/utils/

I’m not sure that if it’s not what you expected? Could you clarify and point out what I missed?

**Comment by ankitkalia1195** [comment]
@nuugut Sorry I forgot to notice that code, my bad. Best of luck

**Comment by gutakk** [comment]
@ankitkalia1195 
It's very pleasure to work with your review here.
Thank you so much

Hope to hear from you guys soon
